import type { MenuItem, MenuCategory } from '@/lib/types';
import { Soup, Beef, GlassWater, Cake, Fish } from 'lucide-react';

export const categories: MenuCategory[] = [
  { id: 'principales', name: 'Brasas', icon: Beef },
  { id: 'chaufa', name: 'Chaufa', icon: Soup },
  { id: 'postres', name: 'Postres', icon: Cake },
];

export const menuItems: MenuItem[] = [
  {
    id: 'lomo-saltado',
    name: 'Lomo Saltado',
    description: 'Trozos de lomo de res salteados con cebolla, tomate, ají amarillo y papas fritas. Acompañado de arroz.',
    price: 55.00,
    category: 'principales',
    image: 'https://images.unsplash.com/photo-1626202425256-02e7379d714d?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'lomo saltado',
  },
  {
    id: 'aji-de-gallina',
    name: 'Ají de Gallina',
    description: 'Pechuga de gallina deshilachada en una cremosa salsa de ají amarillo, pan y leche. Servido con papas y huevo.',
    price: 48.00,
    category: 'principales',
    image: 'https://images.unsplash.com/photo-1604243172027-e95250d4f3b5?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'aji gallina',
  },
  {
    id: 'ceviche-clasico',
    name: 'Ceviche Clásico',
    description: 'Pescado fresco del día marinado en jugo de limón, con cebolla roja, ají limo y cilantro. Acompañado de camote y choclo.',
    price: 52.00,
    category: 'ceviches',
    image: 'https://images.unsplash.com/photo-1633436375795-12b3b339712f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'ceviche peruvian',
  },
  {
    id: 'causa-limena',
    name: 'Causa Limeña de Pollo',
    description: 'Pastel de papa amarilla prensada y sazonada con ají amarillo y limón, relleno de pollo y mayonesa.',
    price: 35.00,
    category: 'entradas',
    image: 'https://images.unsplash.com/photo-1587038995856-1c717725e27d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8cGVydXZpYW4lMjBjYXVzYXxlbnwwfHx8fDE3NjM0Mjg4NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'peruvian causa',
  },
   {
    id: 'pollo-brasa',
    name: 'Pollo a la Brasa',
    description: 'Pollo entero a la parrilla, acompañado con papas fritas, ensalada fresca y cremas especiales.',
    price: 65.00,
    originalPrice: 70.00,
    category: 'principales',
    image: 'https://images.unsplash.com/photo-1599557421888-81d341de5a55?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'roasted chicken salad',
  },
  {
    id: 'medio-pollo-brasa',
    name: '1/2 Pollo a la Brasa',
    description: 'Medio pollo jugoso a la parrilla con papas fritas y ensalada. Ideal para compartir.',
    price: 35.00,
    originalPrice: 42.00,
    category: 'principales',
    image: 'https://images.unsplash.com/photo-1626082912437-d51b3d74a7f7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'half roasted chicken',
  },
  {
    id: 'cuarto-pollo-brasa',
    name: '1/4 Pollo a la Brasa',
    description: 'Cuarto de pollo dorado a la perfección, incluye papas y ensalada.',
    price: 20.00,
    originalPrice: 25.00,
    category: 'principales',
    image: 'https://images.unsplash.com/photo-1626082894179-b4859a584518?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'quarter roasted chicken',
  },
  {
    id: 'pollo-brasa-familiar',
    name: 'Pollo a la Brasa Familiar',
    description: 'Pollo entero + papas grandes + ensalada + 2L de gaseosa. Perfecto para la familia.',
    price: 85.00,
    originalPrice: 95.00,
    category: 'principales',
    image: 'https://images.unsplash.com/photo-1598515598144-b03598912328?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'family roasted chicken',
  },
  {
    id: 'chicha-morada',
    name: 'Chicha Morada',
    description: 'Bebida tradicional peruana hecha de maíz morado, frutas y especias.',
    price: 12.00,
    category: 'bebidas',
    image: 'https://images.unsplash.com/photo-1542518392-13317b1ee2a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwdXJwbGUlMjBkcmlua3xlbnwwfHx8fDE3NjM0Mjg4NTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'purple drink',
  },
  {
    id: 'pisco-sour',
    name: 'Pisco Sour',
    description: 'El cóctel bandera de Perú, preparado con pisco, jugo de limón, jarabe de goma y clara de huevo.',
    price: 28.00,
    category: 'bebidas',
    image: 'https://images.unsplash.com/photo-1620065371451-4d8233e0f8de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxjb2NrdGFpbCUyMGdsYXNzfGVufDB8fHx8MTc2MzQwMDgzOHww&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'cocktail glass',
  },
  {
    id: 'suspiro-limena',
    name: 'Suspiro a la Limeña',
    description: 'Dulce de leche cremoso (manjar blanco) cubierto con un merengue italiano al oporto.',
    price: 25.00,
    category: 'postres',
    image: 'https://images.unsplash.com/photo-1744988870952-3103b7c23649?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxkZXNzZXJ0JTIwZ2xhc3N8ZW58MHx8fHwxNzYzMzMwMDg1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'dessert glass',
  }
];
